version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./seeders:/seeders
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: